name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.21
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build
      run: go build -v ./...
